<?php
require_once '../../config/auth.php'; require_once '../../config/database.php'; requireOsisMember();
$userId=(int)($_SESSION['user_id']??0); $today=date('Y-m-d');
$q=$pdo->prepare("SELECT om.id,om.bagian,s.id student_id,s.nama_lengkap,c.nama_kelas,op.nama_jabatan,ay.tahun_ajaran FROM osis_members om JOIN students s ON s.id=om.student_id LEFT JOIN classes c ON c.id=s.kelas_id JOIN osis_positions op ON op.id=om.position_id JOIN academic_years ay ON ay.id=om.academic_year_id WHERE s.user_id=? AND om.status='aktif' AND ay.status='aktif' ORDER BY om.id DESC LIMIT 1"); $q->execute([$userId]); $profile=$q->fetch(PDO::FETCH_ASSOC)?:[];
$memberId=(int)($profile['id']??0); $studentId=(int)($profile['student_id']??0); $name=$profile['nama_lengkap']??($_SESSION['username']??'Anggota OSIS'); $position=$profile['nama_jabatan']??($_SESSION['jabatan']??'Anggota OSIS');
$totalMembers=(int)$pdo->query("SELECT COUNT(*) FROM osis_members WHERE status='aktif'")->fetchColumn(); $totalActivities=(int)$pdo->query("SELECT COUNT(*) FROM activities WHERE status IN ('rencana','berlangsung')")->fetchColumn(); $totalAnnouncements=(int)$pdo->query("SELECT COUNT(*) FROM announcements WHERE status='publish' AND target IN ('semua','osis')")->fetchColumn();
$news=$pdo->query("SELECT judul,isi,tanggal_publish FROM announcements WHERE status='publish' AND target IN ('semua','osis') ORDER BY tanggal_publish DESC LIMIT 3")->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare("SELECT a.nama_kegiatan,a.tanggal_mulai,a.lokasi,a.status,ac.jabatan_panitia FROM activities a LEFT JOIN activity_committees ac ON ac.activity_id=a.id AND ac.osis_member_id=? WHERE a.status IN ('rencana','berlangsung') ORDER BY (a.tanggal_mulai<?),a.tanggal_mulai LIMIT 4"); $q->execute([$memberId,$today]); $activities=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare("SELECT d.nominal,d.frekuensi,d.bulan,d.minggu_ke,d.tanggal_selesai,p.status payment_status FROM student_dues d LEFT JOIN student_due_payments p ON p.student_due_id=d.id AND p.student_id=? WHERE d.jenis_kas='osis' AND d.status='aktif' AND d.tahun=YEAR(CURDATE()) ORDER BY CASE WHEN d.tanggal_selesai>=CURDATE() THEN 0 ELSE 1 END,d.tanggal_selesai DESC,d.id DESC LIMIT 1"); $q->execute([$studentId]); $cash=$q->fetch(PDO::FETCH_ASSOC)?:null; $cashPaid=$cash&&$cash['payment_status']==='lunas';
$pageTitle='Dashboard Anggota OSIS'; require_once '../../includes/header.php'; require_once '../../includes/osis_sidebar.php'; ?>
<div class="osis-main-content"><header class="osis-topbar member-dashboard-topbar"><button class="btn btn-light d-lg-none" id="osisMenuToggle"><i class="bi bi-list"></i></button><div><strong>Ruang Anggota OSIS</strong><small class="d-block text-muted">Beranda organisasi dan aktivitas Anda</small></div><span class="member-topbar-date"><i class="bi bi-calendar3"></i> <?= date('d M Y') ?></span></header><main class="role-page member-home-page"><div class="role-wrap member-home-wrap">
<section class="member-home-hero"><div><span class="member-home-kicker"><i class="bi bi-stars"></i> Portal Organisasi</span><h1>Halo, <?= htmlspecialchars(explode(' ',trim($name))[0]) ?>!</h1><p>Setiap ide dan kontribusi Anda membantu OSIS menjadi lebih bermakna. Mari lanjutkan hal baik hari ini.</p><span class="member-home-role"><i class="bi bi-patch-check-fill"></i><?= htmlspecialchars($position) ?><?= !empty($profile['bagian'])?' · '.htmlspecialchars($profile['bagian']):'' ?></span></div><div class="member-home-profile"><b><?= htmlspecialchars(strtoupper(substr($name,0,1))) ?></b><strong><?= htmlspecialchars($name) ?></strong><small><i class="bi bi-building"></i> <?= htmlspecialchars($profile['nama_kelas']??'Kelas belum tercatat') ?></small><em>Anggota aktif</em></div></section>
<section class="member-home-stat-grid"><article><i class="blue bi bi-people-fill"></i><div><small>Tim OSIS aktif</small><strong><?= $totalMembers ?></strong><p>anggota dalam organisasi</p></div></article><article><i class="teal bi bi-calendar2-check-fill"></i><div><small>Agenda berjalan</small><strong><?= $totalActivities ?></strong><p>kegiatan siap dijalankan</p></div></article><article><i class="amber bi bi-megaphone-fill"></i><div><small>Informasi OSIS</small><strong><?= $totalAnnouncements ?></strong><p>pengumuman tersedia</p></div></article></section>
<section class="member-home-grid"><article class="member-home-card member-agenda-card"><header><div><span>Agenda terdekat</span><h3>Yang perlu Anda siapkan</h3></div><i class="bi bi-calendar-event"></i></header><div class="member-agenda-list"><?php foreach($activities as $a): ?><div><time><b><?= date('d',strtotime($a['tanggal_mulai'])) ?></b><small><?= strtoupper(date('M',strtotime($a['tanggal_mulai']))) ?></small></time><p><strong><?= htmlspecialchars($a['nama_kegiatan']) ?></strong><span><i class="bi bi-geo-alt"></i> <?= htmlspecialchars($a['lokasi']?:'Lokasi menyusul') ?> · <?= date('H:i',strtotime($a['tanggal_mulai'])) ?> WIB</span><?php if($a['jabatan_panitia']): ?><em><?= htmlspecialchars($a['jabatan_panitia']) ?></em><?php endif ?></p><label class="<?= htmlspecialchars($a['status']) ?>"><?= htmlspecialchars(ucfirst($a['status'])) ?></label></div><?php endforeach; if(!$activities): ?><aside class="member-empty"><i class="bi bi-calendar-x"></i><strong>Belum ada agenda terjadwal</strong><span>Agenda OSIS berikutnya akan muncul di sini.</span></aside><?php endif ?></div></article>
<div class="member-home-side"><article class="member-home-card member-cash-card <?= $cashPaid?'paid':'' ?>"><header><div><span>Status kas OSIS</span><h3><?= $cashPaid?'Kas sudah lunas':'Cek kas Anda' ?></h3></div><i class="bi <?= $cashPaid?'bi-check2-circle':'bi-wallet2' ?>"></i></header><b>Rp <?= $cash?number_format((float)$cash['nominal'],0,',','.'):'—' ?></b><p><?= $cash?($cash['frekuensi']==='mingguan'?'Minggu ke-'.(int)$cash['minggu_ke']:'Kas bulan '.date('F',mktime(0,0,0,(int)$cash['bulan'],1))):'Tagihan kas belum diterbitkan.' ?></p><small><i class="bi <?= $cashPaid?'bi-check-circle-fill':'bi-info-circle-fill' ?>"></i> <?= $cashPaid?'Pembayaran telah tercatat':'Silakan konfirmasi ke bendahara' ?></small></article><article class="member-home-card member-profile-card"><header><div><span>Identitas organisasi</span><h3>Profil keanggotaan</h3></div><i class="bi bi-person-vcard"></i></header><p><i class="bi bi-person-badge"></i> Jabatan <b><?= htmlspecialchars($position) ?></b></p><p><i class="bi bi-mortarboard"></i> Kelas <b><?= htmlspecialchars($profile['nama_kelas']??'-') ?></b></p><p><i class="bi bi-calendar-check"></i> Masa bakti <b><?= htmlspecialchars($profile['tahun_ajaran']??'-') ?></b></p></article></div></section>
<section class="member-home-card member-news-card"><header><div><span>Informasi terbaru</span><h3>Pengumuman untuk OSIS</h3></div><i class="bi bi-bell"></i></header><div><?php foreach($news as $n): ?><article><small><i class="bi bi-clock"></i> <?= date('d M Y',strtotime($n['tanggal_publish'])) ?></small><h4><?= htmlspecialchars($n['judul']) ?></h4><p><?= htmlspecialchars(mb_strimwidth(strip_tags($n['isi']),0,145,'…')) ?></p></article><?php endforeach; if(!$news): ?><aside class="member-empty"><i class="bi bi-megaphone"></i><strong>Belum ada pengumuman</strong></aside><?php endif ?></div></section>
</div></main></div><?php require_once '../../includes/footer.php'; ?>
