<?php
require_once '../../config/auth.php';
require_once '../../config/database.php';
requireLogin();
if (($_SESSION['role'] ?? '') !== 'admin') { header('Location: ../../index.php'); exit; }

$pengurus = $pdo->query("SELECT co.id, co.student_id, co.class_id, co.position, co.academic_year_id, co.tanggal_mulai, co.tanggal_selesai, co.status, s.nama_lengkap, c.nama_kelas, c.tingkat, c.jurusan, COALESCE(NULLIF(d.singkatan, ''), c.jurusan, '') AS jurusan_singkat, ay.tahun_ajaran FROM class_officers co INNER JOIN students s ON s.id = co.student_id INNER JOIN classes c ON c.id = co.class_id INNER JOIN academic_years ay ON ay.id = co.academic_year_id LEFT JOIN departments d ON d.nama_jurusan = c.jurusan ORDER BY co.status DESC, c.nama_kelas ASC, co.position ASC, s.nama_lengkap ASC")->fetchAll(PDO::FETCH_ASSOC);
$totalPengurus = count($pengurus);
$bendaharaAktif = count(array_filter($pengurus, static fn($row) => $row['position'] === 'bendahara_kelas' && $row['status'] === 'aktif'));
$menungguVerifikasi = count(array_filter($pengurus, static fn($row) => $row['status'] === 'menunggu'));
$totalKelas = count(array_unique(array_column($pengurus, 'class_id')));
$pageTitle = 'Bendahara Kelas';
require_once '../../includes/header.php';
require_once '../../includes/sidebar.php';
?>
<main class="main-content">
    <?php require_once '../../includes/navbar.php'; ?>
    <section class="dashboard-container officer-page-modern">
        <section class="officer-page-hero"><div><span class="officer-page-kicker"><i class="bi bi-person-workspace"></i> Administrasi Kelas</span><h2>Bendahara Kelas</h2><p>Pantau penugasan Bendahara Kelas, status verifikasi, dan periode kepengurusan setiap kelas.</p></div><div class="officer-hero-icon"><i class="bi bi-wallet2"></i></div></section>

        <section class="officer-stat-grid"><article><span class="officer-stat-icon blue"><i class="bi bi-person-workspace"></i></span><div><small>Total pengurus</small><strong><?= $totalPengurus ?></strong><p>Data kepengurusan kelas</p></div></article><article><span class="officer-stat-icon teal"><i class="bi bi-wallet2"></i></span><div><small>Bendahara aktif</small><strong><?= $bendaharaAktif ?></strong><p>Sedang bertugas</p></div></article><article><span class="officer-stat-icon amber"><i class="bi bi-clock-history"></i></span><div><small>Menunggu verifikasi</small><strong><?= $menungguVerifikasi ?></strong><p>Perlu ditinjau Admin</p></div></article><article><span class="officer-stat-icon violet"><i class="bi bi-door-open"></i></span><div><small>Kelas tertaut</small><strong><?= $totalKelas ?></strong><p>Kelas memiliki pengurus</p></div></article></section>

        <?php if (isset($_GET['success'])): ?><div class="alert alert-success officer-alert"><i class="bi bi-check-circle-fill"></i><?= $_GET['success'] === 'tambah' ? 'Pengurus kelas berhasil ditambahkan.' : ($_GET['success'] === 'edit' ? 'Data pengurus kelas berhasil diperbarui.' : 'Data pengurus kelas berhasil diarsipkan.') ?></div><?php endif; ?>
        <?php if (isset($_GET['error'])): ?><div class="alert alert-danger officer-alert"><i class="bi bi-exclamation-circle-fill"></i><?= $_GET['error'] === 'hapus' ? 'Data pengurus tidak dapat dihapus.' : 'Terjadi kesalahan atau akses tidak diizinkan.' ?></div><?php endif; ?>

        <section class="officer-list-card"><div class="officer-list-head"><div><span class="eyebrow">Daftar penugasan</span><h4>Bendahara dan pengurus kelas</h4><p>Kelola status kepengurusan dari daftar berikut.</p></div><div class="officer-search"><i class="bi bi-search"></i><input type="search" id="officerSearch" placeholder="Cari nama, kelas, atau jurusan..."></div></div><div class="table-responsive"><table class="table officer-modern-table align-middle mb-0"><thead><tr><th>No.</th><th>Pengurus</th><th>Kelas</th><th>Jabatan</th><th>Tahun ajaran</th><th>Periode</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody id="officerTableBody">
            <?php foreach ($pengurus as $index => $row): $isTreasurer = $row['position'] === 'bendahara_kelas'; ?><tr data-search="<?= htmlspecialchars(strtolower($row['nama_lengkap'] . ' ' . $row['nama_kelas'] . ' ' . $row['jurusan_singkat'])) ?>"><td class="officer-row-number"><?= $index + 1 ?></td><td><div class="officer-profile-cell"><span class="officer-avatar"><?= htmlspecialchars(strtoupper(substr($row['nama_lengkap'], 0, 1))) ?></span><strong><?= htmlspecialchars($row['nama_lengkap']) ?></strong></div></td><td><strong><?= htmlspecialchars($row['nama_kelas']) ?></strong><?php if ($row['jurusan_singkat'] !== ''): ?><small class="d-block officer-department"><i class="bi bi-building"></i> <?= htmlspecialchars($row['jurusan_singkat']) ?></small><?php endif; ?></td><td><span class="officer-position <?= $isTreasurer ? 'treasurer' : 'leader' ?>"><i class="bi <?= $isTreasurer ? 'bi-wallet2' : 'bi-person-badge' ?>"></i><?= $isTreasurer ? 'Bendahara Kelas' : 'Ketua Kelas' ?></span></td><td><?= htmlspecialchars($row['tahun_ajaran']) ?></td><td><span class="officer-period"><strong><?= date('d M Y', strtotime($row['tanggal_mulai'])) ?></strong><small>s/d <?= $row['tanggal_selesai'] ? date('d M Y', strtotime($row['tanggal_selesai'])) : 'Sekarang' ?></small></span></td><td><span class="officer-status <?= htmlspecialchars($row['status']) ?>"><i class="bi bi-circle-fill"></i><?= $row['status'] === 'menunggu' ? 'Menunggu' : htmlspecialchars(ucfirst($row['status'])) ?></span></td><td class="text-end"><div class="officer-action-group"><?php if ($row['position'] === 'ketua_kelas' && $row['status'] === 'menunggu'): ?><form method="post" action="verifikasi_ketua.php" class="d-inline"><input type="hidden" name="id" value="<?= (int) $row['id'] ?>"><button type="submit" name="action" value="setujui" class="btn btn-sm btn-success" title="Setujui ketua kelas"><i class="bi bi-check-lg"></i></button><button type="submit" name="action" value="tolak" class="btn btn-sm btn-light text-danger" title="Tolak ketua kelas"><i class="bi bi-x-lg"></i></button></form><?php endif; ?><a href="edit.php?id=<?= (int) $row['id'] ?>" class="btn btn-sm btn-light text-primary" title="Edit pengurus"><i class="bi bi-pencil-square"></i></a><a href="hapus.php?id=<?= (int) $row['id'] ?>" class="btn btn-sm btn-light text-danger" title="Hapus pengurus" onclick="return confirm('Yakin ingin menghapus data pengurus ini?');"><i class="bi bi-trash"></i></a></div></td></tr><?php endforeach; ?>
            <?php if (!$pengurus): ?><tr><td colspan="8" class="text-center text-muted py-5"><i class="bi bi-person-workspace d-block fs-2 mb-2"></i>Belum ada data pengurus kelas.</td></tr><?php endif; ?><tr id="officerNotFound" class="d-none"><td colspan="8" class="text-center text-muted py-5"><i class="bi bi-search d-block fs-3 mb-2"></i>Pengurus tidak ditemukan.</td></tr>
        </tbody></table></div></section>
    </section>
</main>
<script>document.getElementById('officerSearch')?.addEventListener('input', function () { const keyword = this.value.trim().toLowerCase(); const rows = Array.from(document.querySelectorAll('#officerTableBody tr[data-search]')); let found = 0; rows.forEach(row => { const visible = row.dataset.search.includes(keyword); row.classList.toggle('d-none', !visible); if (visible) found++; }); document.getElementById('officerNotFound')?.classList.toggle('d-none', found !== 0 || keyword === ''); });</script>
<?php require_once '../../includes/footer.php'; ?>
