<?php
require_once '../../config/auth.php'; require_once '../../config/database.php'; requireRole('admin');
$classId=(int)($_GET['id']??0); $department=trim($_GET['jurusan']??''); $month=max(1,min(12,(int)($_GET['bulan']??date('n')))); $year=max(2020,(int)($_GET['tahun']??date('Y')));
$months=[1=>'Januari',2=>'Februari',3=>'Maret',4=>'April',5=>'Mei',6=>'Juni',7=>'Juli',8=>'Agustus',9=>'September',10=>'Oktober',11=>'November',12=>'Desember'];
$classStmt=$pdo->prepare("SELECT id,nama_kelas FROM classes WHERE id=? AND COALESCE(NULLIF(TRIM(jurusan), ''), 'Belum diatur')=? LIMIT 1"); $classStmt->execute([$classId,$department]); $class=$classStmt->fetch(PDO::FETCH_ASSOC);
if(!$class){ header('Location: index.php?bulan='.$month.'&tahun='.$year); exit; }
$studentStmt=$pdo->prepare("SELECT s.nama_lengkap,s.jenis_kelamin,CASE WHEN EXISTS(SELECT 1 FROM student_due_payments p INNER JOIN student_dues d ON d.id=p.student_due_id WHERE p.student_id=s.id AND p.status='lunas' AND d.class_id=? AND d.jenis_kas='kelas' AND d.bulan=? AND d.tahun=? AND d.status='aktif') THEN 'lunas' ELSE 'belum_bayar' END AS status_kas FROM students s WHERE s.kelas_id=? ORDER BY s.nama_lengkap"); $studentStmt->execute([$classId,$month,$year,$classId]); $students=$studentStmt->fetchAll(PDO::FETCH_ASSOC);
$pageTitle='Siswa '.$class['nama_kelas']; require_once '../../includes/header.php'; require_once '../../includes/sidebar.php';
?>
<main class="main-content"><?php require_once '../../includes/navbar.php'; ?><div class="role-page"><div class="role-wrap"><div class="role-hero"><a class="role-back" href="jurusan.php?jurusan=<?= urlencode($department) ?>&bulan=<?= $month ?>&tahun=<?= $year ?>"><i class="bi bi-arrow-left"></i> Rekap Kelas</a><span class="text-uppercase small"><?= htmlspecialchars($department) ?></span><h2><?= htmlspecialchars($class['nama_kelas']) ?></h2><p class="mb-0">Daftar siswa dan status kas bulan <?= $months[$month] ?> <?= $year ?>.</p></div><div class="role-card"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>No</th><th>Nama Siswa</th><th>Jenis Kelamin</th><th>Status Kas</th></tr></thead><tbody><?php foreach($students as $index=>$student): ?><tr><td><?= $index+1 ?></td><td><strong><?= htmlspecialchars($student['nama_lengkap']) ?></strong></td><td><?= $student['jenis_kelamin']==='L'?'Laki-laki':($student['jenis_kelamin']==='P'?'Perempuan':'-') ?></td><td><?php if($student['status_kas']==='lunas'): ?><span class="badge bg-success">Sudah Bayar</span><?php else: ?><span class="badge bg-danger">Belum Bayar</span><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$students): ?><tr><td colspan="4" class="text-center text-muted py-4">Belum ada siswa di kelas ini.</td></tr><?php endif; ?></tbody></table></div></div></div></div></main><?php require_once '../../includes/footer.php'; ?>
